---
- hosts: all
  vars_files:
    - settings.yml
  sudo: yes
  tasks:
    ##
    # APT package installation of required software
    - name: General | Install required packages
      apt: pkg={{ item }} state=installed
      with_items:
        - php5
        - apache2
        - mysql-server
        - mysql-client
        - php5-mysql
        - php-apc
        - php5-xmlrpc
        - php-soap
        - php5-gd
        - unzip
        - python-mysqldb
        - python-pycurl
        - curl
    - include: mysql_secure.yml
    - include: roles/jenkins/main.yml
    - include: roles/php/dev.yml

    ##
    # PHP config
    - name: PHP | Configuration file, php.ini
      template: src=templates/etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini


    ##
    # Apache server configuration
    - name: Apache | enable some required modules
      command: a2enmod rewrite vhost_alias


